// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/insight-landing/DeepRich.tsx": () => import("../components/mockups/insight-landing/DeepRich.tsx"),
  "./components/mockups/insight-landing/PolishedCoherent.tsx": () => import("../components/mockups/insight-landing/PolishedCoherent.tsx")
};
